---
- hosts: all
  tasks:
    - name: Install java
      sudo: true
      apt: pkg=default-jdk update_cache=true force=true
    - name: Add sbt repository
      sudo: true
      apt_repository: repo="deb http://dl.bintray.com/sbt/debian /"
    - name: Install sbt
      sudo: true
      apt: pkg=sbt state=installed update_cache=true force=true
    - name: Install firefox - for browser testing
      sudo: true
      apt: pkg=firefox state=installed update_cache=true force=true
    - name: Install chromium - for browser testing
      sudo: true
      apt: pkg=chromium-browser state=installed update_cache=true force=true
    - name: Packages to get rid of warnings when running headless browser
      sudo: true
      apt: pkg=dbus-x11,xfonts-100dpi,xfonts-75dpi,xfonts-cyrillic state=installed update_cache=true force=true
    - name: Install xvfb - for headless browser testing
      sudo: true
      apt: pkg=xvfb state=installed update_cache=true force=true
    - name: Install nodejs
      sudo: true
      apt: pkg=nodejs state=installed update_cache=true
    - name: Make symlink node->nodejs - this is a temporary measure
      sudo: true
      file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
    - name: Install npm
      sudo: true
      apt: pkg=npm state=installed update_cache=true
    - name: Install source map support for node js
      sudo: true
      npm: name=source-map-support global=true
    - name: Install unzip
      apt:
        name: unzip
        state: latest
        update-cache: yes
      sudo: true
    - name: Make directory for webdriver implementations.
      sudo: true
      file:
        path: /usr/bin/webdrivers
        state: directory
    - name: Make directory for downloads
      sudo: true
      file:
        path: /home/ubuntu/downloads
        state: directory
    #TODO - This use of 'creates' is problematic below as it makes updating the geckodriver to a higher version impossible without
    #manually deleting the geckodriver file from /usr/bin/webdrivers.
    - name: Download geckodriver v0.17.0
      sudo: true
      command: curl -LO https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-linux64.tar.gz
      args:
        chdir: /home/ubuntu/downloads
        creates: /usr/bin/webdrivers/geckodriver
    - name: Unarchive the geckodriver file
      sudo: true
      unarchive:
        src: /home/ubuntu/downloads/geckodriver-v0.17.0-linux64.tar.gz
        dest: /usr/bin/webdrivers
        remote_src: true
        creates: /usr/bin/webdrivers/geckodriver
    - name: Add webdriver directory to system path
      sudo: true
      copy:
        src: webdriver_path.sh
        dest: /etc/profile.d/webdriver_path.sh
    - name: Download chromedriver
      sudo: true
      command: curl -LO https://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
      args:
        chdir: /home/ubuntu/downloads
        creates: /usr/bin/webdrivers/chromedriver
    - name: Unarchive the chromedriver file
      sudo: true
      unarchive:
        src: /home/ubuntu/downloads/chromedriver_linux64.zip
        dest: /usr/bin/webdrivers
        remote_src: true
        creates: /usr/bin/webdrivers/chromedriver
