---
- hosts: all
  tasks:
    - name: Add sbt repository
      sudo: true
      apt_repository: repo="deb http://dl.bintray.com/sbt/debian /"
    - name: Install sbt
      sudo: true
      apt: pkg=sbt state=installed update_cache=true force=true
    - name: Install firefox - for browser testing
      sudo: true
      apt: pkg=firefox=28.0+build2-0ubuntu2 state=installed update_cache=true force=true
    - name: Packages to get rid of warnings when running headless browser
      sudo: true
      apt: pkg=dbus-x11,xfonts-100dpi,xfonts-75dpi,xfonts-cyrillic state=installed update_cache=true force=true
    - name: Install xvfb - for headless browser testing
      sudo: true
      apt: pkg=xvfb state=installed update_cache=true force=true
    - name: Install nodejs
      sudo: true
      apt: pkg=nodejs state=installed update_cache=true
    - name: Make symlink node->nodejs - this is a temporary measure
      sudo: true
      file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
    - name: Install npm
      sudo: true
      apt: pkg=npm state=installed update_cache=true
    - name: Install source map support for node js
      sudo: true
      npm: name=source-map-support global=true
