- name: Install chromium - for browser testing
  apt:
    pkg: chromium-browser
    state: installed
    update_cache: true
    force: true
- name: Install xvfb - for headless browser testing
  apt:
    pkg: xvfb
    state: installed
    update_cache: true
    force: true
- name: Make directory for webdriver implementations.
  file:
    path: /usr/bin/webdrivers
    state: directory
- name: Make directory for downloads
  file:
    path: /home/ubuntu/downloads
    state: directory
- name: Add webdriver directory to system path
  copy:
    src: webdriver_path.sh
    dest: /etc/profile.d/webdriver_path.sh
- name: Install libgconf-2-4 - needed for chromedriver
  apt:
    name: libgconf-2-4
    state: latest
- name: Install unzip - needed for chromedriver download.
  apt:
    name: unzip
    state: latest
    update-cache: yes
# TODO - This use of 'creates' is problematic below as it makes updating chromedriver to a
# higher version impossible without manually deleting the chromedriver file
# from /usr/bin/webdrivers.
- name: Download chromedriver v2.33
  command: curl -LO https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip
  args:
    chdir: /home/ubuntu/downloads
    creates: /usr/bin/webdrivers/chromedriver
- name: Unarchive the chromedriver file
  unarchive:
    src: /home/ubuntu/downloads/chromedriver_linux64.zip
    dest: /usr/bin/webdrivers
    remote_src: true
    creates: /usr/bin/webdrivers/chromedriver
